### PR TITLE
Add thumbnails for Pulstar (Japan)

### PR DESCRIPTION
**Pull request by zcal**
Added box art, snap, and title thumbnails for Pulstar (Japan).

### CODE REVIEW

**Comment by RobLoach** [comment]
Thanks for the contribution, @zcal! Two notes...

1. I see you're using scanlines in the snap and title. We tend to avoid using scanlines on the screenshots and titles.
2. Mind ensuring the images are <= 512px wide? That way they'll render correctly across all the skins.

**Review by RobLoach — CHANGES_REQUESTED** [review]
Sizing, and avoid scanlines 👍

**Comment by zcal** [comment]
@RobLoach Done!  Updated the snap and title to be 512 px wide and with no scanlines or other shader enabled.

**Comment by RobLoach** [comment]
These are incredible! Thanks so much for pushing them forwards.

**Pull request merged**
